### ISSUE TITLE
Sector maps not generating under python 3

### ISSUE THREAD

**Issue by CyberiaResurrection** [makhidkarun/traveller_pyroute#17]
Running ```/usr/bin/python route.py --borders erode --min-btn 15 --pop-code fixed --routes trade --max-jump=5 --speculative-version None --output ../maps --input ../sectors --sectors ../trimlist.txt```, and feeding Zarushagar and Dagudashaag sectors in via trimlist, I get the attached sector maps.  Said maps, when opened in Chrome, are notably lacking in any sort of detail - hex borders, system markers, trade routes, the works.

[Zarushagar Sector.pdf](https://github.com/makhidkarun/traveller_pyroute/files/5002829/Zarushagar.Sector.pdf)
[Dagudashaag Sector.pdf](https://github.com/makhidkarun/traveller_pyroute/files/5002831/Dagudashaag.Sector.pdf)

**Comment by tjoneslo** [comment]
This is a problem with the PyPDF library and the compressed mode. 

The work around is to turn off the compression. [PDF Comression](https://github.com/makhidkarun/traveller_pyroute/blob/master/PyRoute/HexMap.py#L480)  set this to `False` and it should work again. 

The fix is to pull the latest version of [PyPDFLite](https://github.com/katerina7479/pypdflite) from the GitHub repo and install it manually, it's not been released to PyPy. 

I really need to find another PDF writer library.

**Comment by CyberiaResurrection** [comment]
Ok, lemme have a bang at it and see what happens.

**Comment by CyberiaResurrection** [comment]
That's weird - I applied your fix - setting pdf compression to false generated non-blank sector maps, as you said, but subsector map generation packed a mental (and didn't write any subsector maps):

```
2020-08-01 23:22:55,073 - INFO - Charted star count: 1055
2020-08-01 23:22:55,074 - INFO - Charted population 1,207,951
2020-08-01 23:22:55,423 - INFO - writing 2 sector maps...
2020-08-01 23:22:56,105 - INFO - writing 32 subsector maps...
corrupted size vs. prev_size
Aborted (core dumped)
```

**Comment by CyberiaResurrection** [comment]
Possibly a dumb question - by "install pypdflite manually" are you meaning simply copy the files from the repo HEAD over the top of the existing ones?

**Comment by tjoneslo** [comment]
Install pypdflite manually requires:
1. Clone the repo locally, and if you already have, pull the latest of master.
2. run `python3 setup.py install` from the root of the directory. This will install the code into the system, or if you have a venv setup, into the virtual environment.

**Comment by CyberiaResurrection** [comment]
That still doesn't quite work for me. With pdf compression restored, I get the same corrupted size vs prev size error I reported earlier, along with sector maps generating but subsector maps not generating.

**Comment by tjoneslo** [comment]
The Core dump is a different, and much more serious problem. Which version of Python are you using, and which OS?

**Comment by CyberiaResurrection** [comment]
Python 3.7, on 64-bit Fedora 31.

**Comment by tjoneslo** [comment]
First thing I would try is make sure you have the latest versions of all the requirements in requirements.txt. I don't think this will solve the problem, but it is an easy first step. 

If that doesn't work this is some magic incantations the google machine coughed up: 

```
sudo yum install  gperftools-libs
export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
```

Then run the program again. 

If that doesn't work it would be time to break out the debugger and learn how to file bug reports to the Python crew.

**Comment by CyberiaResurrection** [comment]
Here goes.  I was just trying to _profile_ the blasted thing so I could see what low-hanging performance fruit was there to collect.

**Comment by CyberiaResurrection** [comment]
With LD_PRELOAD, looks like all your face are belong to us:

```2020-08-02 01:27:54,934 - INFO - Charted star count: 1055
2020-08-02 01:27:54,934 - INFO - Charted population 1,207,951
2020-08-02 01:27:55,288 - INFO - writing 2 sector maps...
2020-08-02 01:27:57,454 - INFO - writing 32 subsector maps...
Traceback (most recent call last):
  File "/home/alex/gitstuf/traveller_pyroute/PyRoute/route.py", line 143, in <module>
    process()
  File "/home/alex/gitstuf/traveller_pyroute/PyRoute/route.py", line 115, in process
    graphMap.write_maps()
  File "/home/alex/gitstuf/traveller_pyroute/PyRoute/SubsectorMap2.py", line 65, in write_maps
    self.write_base_map(img, subsector)
  File "/home/alex/gitstuf/traveller_pyroute/PyRoute/Map.py", line 204, in write_base_map
    self.subsector_grid(doc, sector)
  File "/home/alex/gitstuf/traveller_pyroute/PyRoute/SubsectorMap2.py", line 86, in subsector_grid
    size = doc.textsize(name, self.titleFont)
  File "/usr/local/lib64/python3.7/site-packages/PIL/ImageDraw.py", line 430, in textsize
    return font.getsize(text, direction, features, language, stroke_width)
  File "/usr/local/lib64/python3.7/site-packages/PIL/ImageFont.py", line 262, in getsize
    size, offset = self.font.getsize(text, False, direction, features, language)
OSError: invalid face handle```

I_think_ this is a walkabout font file, not anything in the python runtime.

**Comment by CyberiaResurrection** [comment]
I think I see the font problem, @tjoneslo  - it's hardcoded and thus doesn't necessarily match up to where the specific font files might be on another box.

**Comment by tjoneslo** [comment]
`sudo yum install dejavu-sans-mono-fonts liberation-fonts gnu-free-fonts gdouros-symbola`

I think this installs all the fonts. The `/usr/share/fonts/truetype/<name>` directory is standard on `ubuntu`. Reading some of the package installs, the yum packages are `/usr/share/fonts/<name>`. 

And, of course, the font names may be different. I'll dig further and see if I can find a better way of doing that.

**Comment by CyberiaResurrection** [comment]
Thanks heaps for your help and patience so far.

**Comment by CyberiaResurrection** [comment]
I'm not sure if this is a fix or a workaround for the font silly buggers, but altering the font lines like so
```
self.namesFont = ImageFont.truetype('/usr/share/fonts/dejavu/DejaVuSerifCondensed.ttf', 32, layout_engine=ImageFont.LAYOUT_BASIC)
```

has fixed the subsector map generation on my box.

**Comment by CyberiaResurrection** [comment]
@tjoneslo , something else seems to have gone boink.

Keeping your LD_PRELOAD suggestion (tweaked to fit my box's setup), manually-installed pypdflite 0.1.41, and dropping back to master HEAD (thus backing out all the code changes I've previously tried) reveals the following with the attached sector file.  

I've tried to trim as much irrelevant stuff out of the sector as I could - I had to rename it to .txt to upload it.

[Trojan Trim.txt](https://github.com/makhidkarun/traveller_pyroute/files/5011680/Trojan.Trim.txt)
```
[alex@crunchbox traveller_pyroute]$ /usr/bin/python3 /home/alex/gitstuf/traveller_pyroute/PyRoute/route.py --borders erode --min-btn 15 --pop-code fixed --routes trade --max-jump=4 --speculative-version None --output maps --input sectors --sectors trimlist.txt
2020-08-02 15:18:45,261 - INFO - starting processing
2020-08-02 15:18:45,262 - INFO - [''sectors/Trojan Trim.sec']
2020-08-02 15:18:45,377 - INFO - Sector Trojan Reach (-4,0) loaded 3 worlds
2020-08-02 15:18:45,384 - INFO - Total number of worlds: 3
2020-08-02 15:18:45,384 - INFO - 1 sectors read
2020-08-02 15:18:45,384 - INFO - generating jumps...
2020-08-02 15:18:45,384 - INFO - base routes: 3  -  ranges: 3
2020-08-02 15:18:45,384 - INFO - calculating routes...
2020-08-02 15:18:45,384 - INFO - Final route count 3
2020-08-02 15:18:45,384 - INFO - setting borders...
2020-08-02 15:18:45,384 - INFO - Processing worlds for erode map drawing
2020-08-02 15:18:45,397 - INFO - sorting routes...
2020-08-02 15:18:45,398 - INFO - processed 1 routes at BTN 16
2020-08-02 15:18:45,398 - INFO - processed 2 routes at BTN 15
2020-08-02 15:18:45,398 - INFO - Processing ETI for worlds
2020-08-02 15:18:45,398 - INFO - Processing TradeGoods for worlds
2020-08-02 15:18:45,398 - INFO - Calculating statistics for 3 worlds
2020-08-02 15:18:45,399 - INFO - Charted star count: 3
2020-08-02 15:18:45,399 - INFO - Charted population 890
2020-08-02 15:18:45,530 - INFO - writing 1 sector maps...
Traceback (most recent call last):
  File "/home/alex/gitstuf/traveller_pyroute/PyRoute/route.py", line 143, in <module>
    process()
  File "/home/alex/gitstuf/traveller_pyroute/PyRoute/route.py", line 111, in process
    pdfmap.write_maps()
  File "/home/alex/gitstuf/traveller_pyroute/PyRoute/HexMap.py", line 77, in write_maps
    self.system(pdf, star)
  File "/home/alex/gitstuf/traveller_pyroute/PyRoute/HexMap.py", line 320, in system
    pdf.add_text(star.name[:chars], point)
  File "/usr/local/lib/python3.7/site-packages/pypdflite/pdfdocument.py", line 255, in add_text
    PDFText(self.session, self.page, text, self.font, self.text_color, cursor, justification, self.double_spacing)
  File "/usr/local/lib/python3.7/site-packages/pypdflite/pdfobjects/pdftext.py", line 22, in __init__
    if self._test_x_fit() is True:
  File "/usr/local/lib/python3.7/site-packages/pypdflite/pdfobjects/pdftext.py", line 128, in _test_x_fit
    test = self.cursor.x_fit(self.font._string_width(self.text))
  File "/usr/local/lib/python3.7/site-packages/pypdflite/pdfobjects/pdffont.py", line 139, in _string_width
    w += self.character_widths[i]
KeyError: '’'
```

**Comment by tjoneslo** [comment]
This is a known issue in the Traveller Map data. See : https://github.com/inexorabletash/travellermap/pull/185 where the issue is fixed in the data. For your data you need to change the `’` character to an apostrophe `'`.

**Comment by CyberiaResurrection** [comment]
Sorry for the delay.  Hand-hacking that fix got past that error.
